name: Python

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create artifact directory
        run: mkdir -p path/to/artifact

      - name: Display Python versions
        run: |
          versions="${{ matrix.python-version }}"
          versions_array=(${versions// / })
          for version in "${versions_array[@]}"; do
            echo "Python $version" >> ${{ github.workspace }}/path/to/artifact/world.txt
            python$version -c "import sys; print(sys.version)" >> ${{ github.workspace }}/path/to/artifact/world.txt
            echo >> ${{ github.workspace }}/path/to/artifact/world.txt
          done
     
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact
